# -*- coding: utf-8 -*-
"""The Syntax Surgeon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeTmOXoL67Oka_8hQh0V1cg6XjuHMZtl
"""

!pip install gradio

import ast

def check_syntax(code):
    try:
        ast.parse(code)
        return "✅ No Syntax Error Found"
    except SyntaxError as e:
        return f"❌ Syntax Error: {e}"

import gradio as gr

interface = gr.Interface(
    fn=check_syntax,
    inputs=gr.Textbox(lines=10, placeholder="Enter Python Code Here"),
    outputs="text",
    title="The Syntax Surgeon",
    description="Check Python code for syntax errors"
)

interface.launch()